### ISSUE TITLE
Doplnení času do identifikace draftu.

### ISSUE THREAD

**Issue by kaklik** [olsak/CTUstyle3#3]
Děkuji za tuto šablonu, už několikrát jsem ji využil. 

Měl bych zároveň návrh na zlepšení.  V případě draftu by se myslím hodilo, kdyby v dokumentu kromě označení  

![image](https://github.com/olsak/CTUstyle3/assets/1194177/ddef85b4-5208-4af4-9f3f-f45356f6fd9b)

Byl i čas.  Nevím jestli je to pouze můj případ, ale zejména s blížícím se termínem odevzdání práce vzniká ve stejném dni mnoho verzí, které je nyní obtížné odlišit, když rozlišení identifikace je na úrovni dne.

**Comment by olsak** [comment]
Dekuji za tip, implementoval jsem to. Viz posledni commit  https://github.com/olsak/CTUstyle3/commit/1e6288e66f7de3cf41f9b056596ed00c40383d35

**Comment by kaklik** [comment]
Velmi děkuji za implementaci!  Hned jsem to [vyzkoušel](https://github.com/kaklik/Thesis/blob/disertation/disertation.pdf) a mohu potvrdit, že to funguje: 

![image](https://github.com/olsak/CTUstyle3/assets/1194177/2436766d-e776-4783-8320-ed81786d0cad)

**Comment by olsak** [comment]
Jeste jsem si uvedomil chybu. Minuty je treba formatovat specialne jako 00, 01, 02, ..., 59 (ta nula vpredu). Doplnil jsem to az nyni.
