### ISSUE TITLE
Sekce mimo obsah

### ISSUE THREAD

**Issue by kaklik** [olsak/CTUstyle3#5]
Rád bych měl sekci mimo faktický obsah práce.   V angličtině jsem takovou sekci pojmenoval jako Foreword. Vzhledem k její povaze bych chtěl, aby byla nečíslována a zároven i mimo hlavní obsah. Proto jsem ji vytvořil následujícím způsobem hned za úvodní stranou: 

    \sec \notoc \nonum Foreword 

Pozoruji ale zvláštní chování, kdy tímto způsobem vytvořená sekce je při následném TeXování vysázena buď s číslováním. To znamená takto: 

![image](https://github.com/olsak/CTUstyle3/assets/1194177/e1f5b11c-e9e0-41f6-b5c9-26f0813fc5f5)

A nebo je přítomná v absahu práce, takto: 

![image](https://github.com/olsak/CTUstyle3/assets/1194177/6f229ac0-6bc9-4835-8370-a944dfd71f51)

Tyto dva stavy mezi sebou vzájemně komutují s každým dalším spuštěním `optex minimal`.  Jak je vidět zde: 

![image](https://github.com/olsak/CTUstyle3/assets/1194177/426426fe-c974-4942-b6d6-a30fead9770e)

![image](https://github.com/olsak/CTUstyle3/assets/1194177/88c49fb5-da35-4f8e-bc72-4610ca278e77)

Zřejmě ale nelze dosáhnout očekávaného stavu, že sekce nebude číslována a zároveň nebude přítomná v TOC. 

Pro snazší zreplikování situce přikládám niminální dokument.
 

[minimal.tex.txt](https://github.com/user-attachments/files/16044701/minimal.tex.txt)

[minimal.pdf](https://github.com/user-attachments/files/16044702/minimal.pdf)

**Comment by olsak** [comment]
Správné použití je
```
\notoc \nonum \sec
```
tedy pokyny `\notoc` a `\nonum` předchází `\sec`.

**Comment by kaklik** [comment]
> Správné použití je
> 
> ```
> \notoc \nonum \sec
> ```
> 
> tedy pokyny `\notoc` a `\nonum` předchází `\sec`.

Ano, opravdu to pak funguje.   

Děkuji!
